# Generated by Django 4.2.4 on 2023-08-12 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=10)),
                ('address', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, default='')),
                ('max_capacity', models.IntegerField(default=-1)),
                ('exists', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('show_start', models.DateTimeField()),
                ('doors_open', models.DateTimeField(blank=True, default=None)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue')),
            ],
        ),
        migrations.CreateModel(
            name='OpenMic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('description', models.TextField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue')),
            ],
        ),
    ]
