# Generated by Django 4.2.4 on 2024-07-14 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
  dependencies = [
    ("api", "0001_initial"),
  ]

  operations = [
    migrations.CreateModel(
      name="JanitorApplyArtistRecord",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("artists", models.ManyToManyField(to="api.artist")),
        ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.event")),
      ],
    ),
    migrations.CreateModel(
      name="JanitorMergeEventRecord",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("from_events", models.ManyToManyField(related_name="from_events", to="api.event")),
        ("to_event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="to_event", to="api.event")),
      ],
    ),
    migrations.CreateModel(
      name="JanitorRun",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("finished_at", models.DateTimeField(blank=True, null=True)),
        ("name", models.CharField(max_length=64)),
      ],
    ),
    migrations.AddField(
      model_name="carpenterrun",
      name="finished_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.AddField(
      model_name="ingestionrun",
      name="finished_at",
      field=models.DateTimeField(blank=True, null=True),
    ),
    migrations.CreateModel(
      name="JanitorRecord",
      fields=[
        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
        ("created_at", models.DateTimeField(auto_now_add=True)),
        ("operation", models.CharField(choices=[("Apply Artists", "Apply Artists"), ("Merge Events", "Merge Events")], max_length=16)),
        ("change_log", models.TextField(blank=True, null=True)),
        (
          "apply_artists_record",
          models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.janitorapplyartistrecord"),
        ),
        ("janitor_run", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="api.janitorrun")),
        (
          "merge_event_record",
          models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="api.janitormergeeventrecord"),
        ),
      ],
    ),
  ]
