# Generated by Django 4.2.4 on 2023-08-13 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_openmic_crontab_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openmic',
            name='title',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='doors_open',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
