# Generated by Django 4.2.4 on 2024-07-17 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_m2m_to_o2m'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janitormergeeventrecord',
            name='from_events',
        ),
    ]
