# Generated by Django 4.2.4 on 2023-08-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_openmic_title_alter_show_doors_open_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='show_start',
        ),
        migrations.AddField(
            model_name='show',
            name='show_day',
            field=models.DateField(default='2023-08-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='start_time',
            field=models.TimeField(default='20:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='show',
            name='doors_open',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
