# Generated by Django 4.2.4 on 2023-08-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_show_show_start_show_show_day_show_start_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('venue', 'show_day')},
        ),
        migrations.AlterUniqueTogether(
            name='venue',
            unique_together={('latitude', 'longitude')},
        ),
    ]
