# Generated by Django 4.2.4 on 2024-07-28 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_janitormergeeventrecord_from_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenterrecord',
            name='open_mic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.openmic'),
        ),
        migrations.AlterField(
            model_name='carpenterrecord',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rawdata'),
        ),
    ]
