# Generated by Django 4.2.4 on 2023-10-10 02:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_show_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('Open Mic', 'Open Mic'), ('Show', 'Show')], default='Show', max_length=16)),
                ('title', models.CharField(max_length=256)),
                ('event_day', models.DateField()),
                ('start_time', models.TimeField()),
                ('doors_open', models.TimeField(blank=True, default=None, null=True)),
                ('ticket_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue')),
            ],
        ),
        migrations.DeleteModel(
            name='Show',
        ),
    ]
