# Generated by Django 4.2.4 on 2023-10-10 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_event_delete_show'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenMic',
            new_name='OpenMicGenerator',
        ),
    ]
