# Generated by Django 4.2.4 on 2024-10-01 03:39

from django.db import migrations, models

from api.constants import DAY_CHOICES
from api.models import OpenMic


class Migration(migrations.Migration):
  dependencies = [
    ("api", "0008_ingestionrun_metadata"),
  ]

  def undo(apps, schema_editor):
    # Don't need to do anything, this field will get dropped when we
    # apply the reverse operation.
    pass

  def update_mic_day(apps, schema_editor):
    for mic in OpenMic.objects.all():
      for day, _ in DAY_CHOICES:
        if day[:3].lower() in mic.cadence_crontab.lower():
          mic.day = day
          mic.save()
          break

  operations = [
    migrations.AddField(
      model_name="openmic",
      name="day",
      field=models.CharField(
        blank=True,
        null=True,
        choices=[
          ("Sunday", "Sunday"),
          ("Monday", "Monday"),
          ("Tuesday", "Tuesday"),
          ("Wednesday", "Wednesday"),
          ("Thursday", "Thursday"),
          ("Friday", "Friday"),
          ("Saturday", "Saturday"),
        ],
        max_length=16,
      ),
    ),
    migrations.RunPython(update_mic_day, undo),
    migrations.AlterField(
      model_name="openmic",
      name="day",
      field=models.CharField(
        choices=[
          ("Sunday", "Sunday"),
          ("Monday", "Monday"),
          ("Tuesday", "Tuesday"),
          ("Wednesday", "Wednesday"),
          ("Thursday", "Thursday"),
          ("Friday", "Friday"),
          ("Saturday", "Saturday"),
        ],
        max_length=16,
      ),
    ),
  ]
