# Generated by Django 4.2.4 on 2023-10-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_openmic_openmicgenerator'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('VenuePilot', 'VenuePilot'), ('EventBrite', 'EventBrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_id',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
