# Generated by Django 4.2.4 on 2023-10-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_venue_venue_api_venue_venue_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='venue_id',
            new_name='venue_api_id',
        ),
    ]
