# Generated by Django 4.2.4 on 2024-11-18 04:23

from django.db import migrations, models

from api.models import OpenMic


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_openmic_day"),
    ]

    def undo(apps, schema_editor):
      # Don't need to do anything, this field will get dropped when we
      # apply the reverse operation.
      pass

    def update_mic_slugs(apps, schema_editor):
      for mic in OpenMic.objects.all():
         mic.make_pretty()
         mic.save()

    operations = [
        migrations.AddField(
            model_name="openmic",
            name="slug",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="openmic",
            name="day",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                default="Sunday",
                max_length=16,
            ),
        ),
        migrations.RunPython(update_mic_slugs, undo),
        migrations.AlterField(model_name="openmic", name="slug", field=models.CharField(max_length=128, unique=True), preserve_default=False),
    ]
