# Generated by Django 4.2.4 on 2023-10-10 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_venue_id_venue_venue_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='Seattle', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venue',
            name='postal_code',
            field=models.CharField(default=98107, max_length=8),
            preserve_default=False,
        ),
    ]
