# Generated by Django 4.2.4 on 2023-10-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('venue', 'title')},
        ),
    ]
