# Generated by Django 4.2.4 on 2023-10-10 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_event_start_time_alter_event_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ticket_price',
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_max',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price_min',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
