# Generated by Django 4.2.4 on 2023-10-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_event_ticket_price_event_ticket_price_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
