# Generated by Django 4.2.4 on 2023-10-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_venue_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=128, unique=True)),
                ('proper_name', models.CharField(max_length=128)),
            ],
        ),
    ]
