# Generated by Django 4.2.4 on 2023-10-11 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_venuealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuealias',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
        ),
    ]
