# Generated by Django 4.2.4 on 2023-10-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_event_venue_alter_openmicgenerator_venue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='exists',
            new_name='gather_data',
        ),
        migrations.AddField(
            model_name='venue',
            name='show_venue',
            field=models.BooleanField(default=True),
        ),
    ]
