# Generated by Django 4.2.4 on 2023-10-14 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_rename_exists_venue_gather_data_venue_show_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_url',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
