# Generated by Django 4.2.4 on 2023-10-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_event_event_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('VenuePilot', 'VenuePilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
