# Generated by Django 4.2.4 on 2023-10-15 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_venue_venue_api'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_api',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_api_id',
        ),
        migrations.AddField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('VenuePilot', 'VenuePilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.CreateModel(
            name='VenueApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_api', models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('VenuePilot', 'VenuePilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('venue_api_id', models.CharField(blank=True, max_length=32, null=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue')),
            ],
        ),
    ]
