# Generated by Django 4.2.4 on 2023-10-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_venue_venue_api_remove_venue_venue_api_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='venueapi',
            unique_together={('venue', 'venue_api')},
        ),
    ]
