# Generated by Django 4.2.4 on 2023-10-15 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_venueapi_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venueapi',
            old_name='venue_api_id',
            new_name='api_id',
        ),
        migrations.RenameField(
            model_name='venueapi',
            old_name='venue_api',
            new_name='api_name',
        ),
        migrations.AlterUniqueTogether(
            name='venueapi',
            unique_together={('venue', 'api_name')},
        ),
    ]
