# Generated by Django 4.2.4 on 2023-10-17 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_venue_api_id_venueapi_api_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proper_name', models.CharField(max_length=128, unique=True)),
                ('match', models.JSONField(max_length=256)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.DeleteModel(
            name='VenueAlias',
        ),
    ]
