# Generated by Django 4.2.4 on 2023-10-17 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_venuemask_alter_event_event_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemask',
            name='address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
