# Generated by Django 4.2.4 on 2023-10-17 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_venuemask_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemask',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='venuemask',
            name='postal_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
