# Generated by Django 4.2.4 on 2023-10-20 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_venuemask_city_venuemask_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('AXS', 'AXS'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('AXS', 'AXS'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
