# Generated by Django 4.2.4 on 2023-10-26 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_event_description_alter_event_event_api_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('venue', 'title', 'event_day', 'start_time')},
        ),
        migrations.AddField(
            model_name='event',
            name='is_ticketed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('AXS', 'AXS'), ('OpenMicGenerator', 'OpenMicGenerator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='ticket_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('Crawler', 'Crawler'), ('AXS', 'AXS'), ('OpenMicGenerator', 'OpenMicGenerator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
