# Generated by Django 4.2.4 on 2023-10-26 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_event_unique_together_event_is_ticketed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('open_mic_type', models.CharField(choices=[('All', 'All'), ('Comdey', 'Comedy'), ('Music', 'Music'), ('Spoken Word', 'Spoken Word')], default='Music', max_length=16)),
                ('description', models.TextField()),
                ('signup_start_time', models.TimeField()),
                ('event_start_time', models.TimeField()),
                ('event_end_time', models.TimeField()),
                ('all_ages', models.BooleanField(default=False)),
                ('house_piano', models.BooleanField(default=False)),
                ('house_pa', models.BooleanField(default=True)),
                ('cadence_crontab', models.CharField(max_length=64)),
                ('cadence_readable', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(default='Bar', max_length=32),
        ),
        migrations.DeleteModel(
            name='OpenMicGenerator',
        ),
        migrations.AddField(
            model_name='openmic',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
    ]
