# Generated by Django 4.2.4 on 2023-10-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_openmic_event_end_time_venue_venue_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='show_event',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='openmic',
            name='generate_events',
            field=models.BooleanField(default=True),
        ),
    ]
