# Generated by Django 4.2.4 on 2023-10-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_event_signup_start_time_alter_openmic_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venupilot', 'Venupilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Open Mic Generator', 'Open Mic Generator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='openmic',
            name='open_mic_type',
            field=models.CharField(choices=[('All', 'All'), ('Comedy', 'Comedy'), ('Music', 'Music'), ('Spoken Word', 'Spoken Word')], default='Music', max_length=16),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venupilot', 'Venupilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Open Mic Generator', 'Open Mic Generator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
