# Generated by Django 4.2.4 on 2023-10-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_event_event_api_alter_openmic_open_mic_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Open Mic Generator', 'Open Mic Generator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Open Mic Generator', 'Open Mic Generator'), ('Manual', 'Manual')], default='Manual', max_length=20),
        ),
    ]
