# Generated by Django 4.2.4 on 2023-10-28 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_event_event_api_alter_venueapi_api_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='APISample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('api_name', models.CharField(choices=[('Ticketmaster', 'Ticketmaster'), ('Venuepilot', 'Venuepilot'), ('Eventbrite', 'Eventbrite'), ('TIXR', 'TIXR'), ('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Open Mic Generator', 'Open Mic Generator'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('data', models.JSONField()),
            ],
        ),
    ]
