# Generated by Django 4.2.4 on 2023-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_apisample'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisample',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
