# Generated by Django 4.2.4 on 2023-10-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_apisample_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisample',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
