# Generated by Django 4.2.4 on 2023-10-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_remove_apisample_date_apisample_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openmic',
            name='drums',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Coffee Shop', 'Coffee Shop'), ('Event Space', 'Event Space')], default='Bar', max_length=32),
        ),
    ]
