# Generated by Django 4.2.4 on 2023-11-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_openmic_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueapi',
            name='crawler_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
