# Generated by Django 4.2.4 on 2023-11-07 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_event_cash_only_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('venue', 'event_day', 'start_time')},
        ),
    ]
