# Generated by Django 4.2.4 on 2023-11-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisample',
            name='api_name',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
    ]
