# Generated by Django 4.2.4 on 2023-11-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_apisample_api_name_alter_event_event_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
