# Generated by Django 4.2.4 on 2023-11-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_rename_event_image_event_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='venue_image_url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
