# Generated by Django 4.2.4 on 2023-11-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_venue_venue_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='event_images'),
        ),
    ]
