# Generated by Django 4.2.4 on 2023-11-23 03:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_venuetags_eventtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='openmic',
            name='event_mic_type',
            field=models.CharField(choices=[('Open Jam', 'Open Jam'), ('Open Mic', 'Open Mic'), ('Show', 'Show')], default='Open Mic', max_length=32),
        ),
        migrations.AddField(
            model_name='venuetags',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Open Jam', 'Open Jam'), ('Open Mic', 'Open Mic'), ('Show', 'Show')], default='Show', max_length=16),
        ),
        migrations.AlterField(
            model_name='eventtags',
            name='event_type',
            field=models.CharField(choices=[('Open Jam', 'Open Jam'), ('Open Mic', 'Open Mic'), ('Show', 'Show')], max_length=32),
        ),
    ]
