# Generated by Django 4.2.4 on 2023-11-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_eventtags_created_at_openmic_event_mic_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventTags',
        ),
    ]
