# Generated by Django 4.2.4 on 2023-11-23 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_delete_eventtags'),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('venue_type', models.CharField(choices=[('Bar', 'Bar'), ('Brewery', 'Brewery'), ('Coffee Shop', 'Coffee Shop'), ('Event Space', 'Event Space'), ('Shop', 'Shop')], max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_type',
            field=models.CharField(choices=[('Bar', 'Bar'), ('Brewery', 'Brewery'), ('Coffee Shop', 'Coffee Shop'), ('Event Space', 'Event Space'), ('Shop', 'Shop')], default='Bar', max_length=32),
        ),
        migrations.DeleteModel(
            name='VenueTags',
        ),
        migrations.AddField(
            model_name='venuetag',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
        ),
        migrations.AlterUniqueTogether(
            name='venuetag',
            unique_together={('venue', 'venue_type')},
        ),
    ]
