# Generated by Django 4.2.4 on 2023-11-23 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_venuetag_alter_venue_venue_type_delete_venuetags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
    ]
