# Generated by Django 4.2.4 on 2023-11-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_remove_venue_venue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='venue_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='venuetag',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_tags', to='api.venue'),
        ),
    ]
