# Generated by Django 4.2.4 on 2024-02-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0059_venue_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apisample',
            name='api_name',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_api',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='venue',
            name='neighborhood',
            field=models.CharField(blank=True, choices=[('Ballard', 'Ballard'), ('Belltown', 'Belltown'), ('Capitol Hill', 'Capitol Hill'), ('Downtown', 'Downtown'), ('Fremont', 'Fremont'), ('Greenlake', 'Greenlake'), ('Magnolia', 'Magnolia'), ('Phinney Ridge', 'Phinney Ridge'), ('Queen Anne', 'Queen Anne'), ('University District', 'University District'), ('West Seattle', 'West Seattle')], max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='venueapi',
            name='api_name',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20),
        ),
    ]
