# Generated by Django 4.2.4 on 2024-02-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_alter_apisample_api_name_alter_event_event_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='name_lower',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
