# Generated by Django 4.2.4 on 2024-02-12 19:51

from django.db import migrations, models

from api.models import Venue


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0061_venue_name_lower'),
    ]

    def venue_names_to_lower(apps, schema_editor):
        for venue in Venue.objects.all():
            venue.name_lower = venue.name.lower()
            venue.save()

    operations = [
        migrations.RunPython(venue_names_to_lower),
    ]
