# Generated by Django 4.2.4 on 2024-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_populate_venue_name_lower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name_lower',
            field=models.CharField(default='asdf', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
