# Generated by Django 4.2.4 on 2024-03-08 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0065_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRecordBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_name', models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20)),
                ('change_type', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Error', 'Error'), ('Update', 'Update')], max_length=16)),
                ('change_log', models.TextField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingestionrun')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionRecordVenue',
            fields=[
                ('ingestionrecordbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ingestionrecordbase')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue')),
            ],
            bases=('api.ingestionrecordbase',),
        ),
        migrations.CreateModel(
            name='IngestionRecordEvent',
            fields=[
                ('ingestionrecordbase_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.ingestionrecordbase')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.event')),
            ],
            bases=('api.ingestionrecordbase',),
        ),
    ]
