# Generated by Django 4.2.4 on 2024-03-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_ingestionrun_ingestionrecordbase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='name',
            field=models.CharField(default='asdf', max_length=64),
            preserve_default=False,
        ),
    ]
