# Generated by Django 4.2.4 on 2024-03-08 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_ingestionrun_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrecordbase',
            name='change_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Error', 'Error'), ('NO OP', 'NO OP'), ('Skip', 'Skip'), ('Update', 'Update')], max_length=16),
        ),
        migrations.AlterField(
            model_name='ingestionrecordevent',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.event'),
        ),
        migrations.AlterField(
            model_name='ingestionrecordvenue',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.venue'),
        ),
    ]
