# Generated by Django 4.2.4 on 2024-03-09 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0068_alter_ingestionrecordbase_change_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRecordAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_name', models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20)),
                ('change_type', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Error', 'Error'), ('NO OP', 'NO OP'), ('Skip', 'Skip'), ('Update', 'Update')], max_length=16)),
                ('record_type', models.CharField(choices=[('Event', 'Event'), ('Venue', 'Venue')], max_length=16)),
                ('count', models.IntegerField()),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingestionrun')),
            ],
            options={
                'unique_together': {('ingestion_run', 'api_name', 'change_type', 'record_type')},
            },
        ),
    ]
