# Generated by Django 4.2.4 on 2024-03-09 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_ingestionrecordaggregate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrecordaggregate',
            name='api_name',
            field=models.CharField(default='Manual', max_length=32),
        ),
    ]
