# Generated by Django 4.2.4 on 2024-03-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_alter_ingestionrecordaggregate_api_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrecordbase',
            name='api_name',
            field=models.CharField(default='Manual', max_length=32),
        ),
    ]
