# Generated by Django 4.2.4 on 2024-04-14 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0072_ingestionrecord_remove_ingestionrecordevent_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingestionrecordbase',
            name='ingestion_run',
        ),
        migrations.DeleteModel(
            name='IngestionRecordAggregate',
        ),
        migrations.DeleteModel(
            name='IngestionRecordBase',
        ),
    ]
