# Generated by Django 4.2.4 on 2024-04-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0073_remove_ingestionrecordbase_ingestion_run_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
    ]
