# Generated by Django 4.2.4 on 2024-04-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0074_alter_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='venue_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images'),
        ),
    ]
