# Generated by Django 4.2.4 on 2024-04-25 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_alter_venue_venue_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingestionrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event'),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
    ]
