# Generated by Django 4.2.4 on 2024-05-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0076_alter_ingestionrecord_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='match',
            field=models.JSONField(blank=True, max_length=1024, null=True),
        ),
    ]
