# Generated by Django 4.2.4 on 2024-05-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0079_delete_venuemask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='alias',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
