# Generated by Django 4.2.4 on 2024-06-14 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0081_rawevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
