# Generated by Django 4.2.4 on 2024-06-14 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0082_rawevent_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='cash_only',
        ),
        migrations.RemoveField(
            model_name='event',
            name='doors_open',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_api',
        ),
        migrations.RemoveField(
            model_name='event',
            name='is_ticketed',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price_max',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ticket_price_min',
        ),
    ]
