# Generated by Django 4.2.4 on 2024-06-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0083_remove_event_cash_only_remove_event_doors_open_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_lower', models.CharField(max_length=128, unique=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(max_length=256)),
                ('postal_code', models.CharField(max_length=8)),
                ('city', models.CharField(max_length=64)),
                ('venue_url', models.CharField(blank=True, max_length=256, null=True)),
                ('venue_image_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='venue_images')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('venue_api', models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20)),
            ],
            options={
                'unique_together': {('venue_api', 'latitude', 'longitude')},
            },
        ),
    ]
