# Generated by Django 4.2.4 on 2024-06-14 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0085_remove_venue_gather_data_remove_venue_max_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawvenue',
            name='finalized_venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='api.venue'),
        ),
    ]
