# Generated by Django 4.2.4 on 2024-06-14 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0086_rawvenue_finalized_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawevent',
            name='venue_api_id',
        ),
        migrations.RemoveField(
            model_name='rawevent',
            name='venue_name',
        ),
        migrations.AddField(
            model_name='rawevent',
            name='raw_venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.venue'),
            preserve_default=False,
        ),
    ]
