# Generated by Django 4.2.4 on 2024-06-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_remove_rawevent_venue_api_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rawvenue',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rawvenue',
            name='finalized_venue',
        ),
        migrations.DeleteModel(
            name='RawEvent',
        ),
        migrations.DeleteModel(
            name='RawVenue',
        ),
    ]
