# Generated by Django 4.2.4 on 2024-06-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0089_artist_sociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='artists',
            field=models.ManyToManyField(to='api.artist'),
        ),
    ]
