# Generated by Django 4.2.4 on 2024-06-16 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_event_artists'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_name', models.CharField(choices=[('AXS', 'AXS'), ('Crawler', 'Crawler'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=20)),
                ('event_api_id', models.CharField(max_length=64)),
                ('event_name', models.CharField(max_length=256)),
                ('venue_name', models.CharField(max_length=128)),
                ('data', models.JSONField()),
            ],
            options={
                'unique_together': {('api_name', 'event_api_id')},
            },
        ),
    ]
