# Generated by Django 4.2.4 on 2024-06-16 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_crawler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VenueApi',
        ),
    ]
