# Generated by Django 4.2.4 on 2024-06-16 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0093_delete_venueapi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='APISample',
        ),
    ]
