# Generated by Django 4.2.4 on 2024-06-17 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0096_remove_ingestionrecord_change_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrecord',
            name='change_log',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionrecord',
            name='change_type',
            field=models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Error', 'Error'), ('NO OP', 'NO OP'), ('Skip', 'Skip'), ('Update', 'Update')], default='skip', max_length=16),
            preserve_default=False,
        ),
    ]
