# Generated by Django 4.2.4 on 2024-06-17 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_ingestionrecord_change_log_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='name_slug',
            field=models.CharField(default='asdf', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
