# Generated by Django 4.2.4 on 2024-06-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_rawdata_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='raw_datas',
            field=models.ManyToManyField(to='api.rawdata'),
        ),
    ]
