# Generated by Django 4.2.4 on 2024-07-02 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0101_alter_janitorrecord_field_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='artist_image',
            field=models.ImageField(blank=True, null=True, upload_to='event_images'),
        ),
        migrations.AddField(
            model_name='artist',
            name='artist_image_url',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='ingestionrecord',
            name='raw_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.rawdata'),
        ),
        migrations.AlterField(
            model_name='rawdata',
            name='api_name',
            field=models.CharField(choices=[('AXS', 'AXS'), ('Bandsintown', 'Bandsintown'), ('Crawler - Blue Moon', 'Crawler - Blue Moon'), ("Crawler - Darrell's Tavern", "Crawler - Darrell's Tavern"), ('Crawler - Little Red Hen', 'Crawler - Little Red Hen'), ('Crawler - Sea Monster Lounge', 'Crawler - Sea Monster Lounge'), ('Crawler - Skylark', 'Crawler - Skylark'), ('Crawler - The Royal Room', 'Crawler - The Royal Room'), ('Dice', 'Dice'), ('Eventbrite', 'Eventbrite'), ('Manual', 'Manual'), ('Open Mic Generator', 'Open Mic Generator'), ('Songkick', 'Songkick'), ('Ticketmaster', 'Ticketmaster'), ('TIXR', 'TIXR'), ('Venuepilot', 'Venuepilot')], default='Manual', max_length=32),
        ),
    ]
