# Generated by Django 4.2.4 on 2024-07-05 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_alter_venue_latitude_alter_venue_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpenterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_name', models.CharField(default='Manual', max_length=32)),
                ('change_type', models.CharField(choices=[('Create', 'Create'), ('Delete', 'Delete'), ('Error', 'Error'), ('NO OP', 'NO OP'), ('Skip', 'Skip'), ('Update', 'Update')], max_length=16)),
                ('change_log', models.TextField(blank=True, null=True)),
                ('field_changed', models.CharField(choices=[('event', 'event'), ('venue', 'venue'), ('artist', 'artist'), ('none', 'none')], max_length=32)),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.artist')),
            ],
        ),
        migrations.RenameModel(
            old_name='JanitorRun',
            new_name='CarpenterRun',
        ),
        migrations.DeleteModel(
            name='JanitorRecord',
        ),
        migrations.AddField(
            model_name='carpenterrecord',
            name='carpenter_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.carpenterrun'),
        ),
        migrations.AddField(
            model_name='carpenterrecord',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.event'),
        ),
        migrations.AddField(
            model_name='carpenterrecord',
            name='raw_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rawdata'),
        ),
        migrations.AddField(
            model_name='carpenterrecord',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.venue'),
        ),
    ]
