# Generated by Django 4.2.4 on 2024-07-05 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_carpenterrecord_rename_janitorrun_carpenterrun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
