# Generated by Django 4.2.4 on 2024-07-07 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_event_finalized_rawdata_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanitorApplyArtistRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artists', models.ManyToManyField(to='api.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='JanitorMergeEventRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_events', models.ManyToManyField(related_name='from_events', to='api.event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_event', to='api.event')),
            ],
        ),
        migrations.CreateModel(
            name='JanitorRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='api.artist'),
        ),
        migrations.CreateModel(
            name='JanitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operation', models.CharField(choices=[('Apply Artists', 'Apply Artists'), ('Merge Events', 'Merge Events')], max_length=16)),
                ('apply_artists_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.janitorapplyartistrecord')),
                ('janitor_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.janitorrun')),
                ('merge_event_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.janitormergeeventrecord')),
            ],
        ),
    ]
