# Generated by Django 4.2.4 on 2024-07-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0106_janitorapplyartistrecord_janitormergeeventrecord_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='janitorrecord',
            name='change_log',
            field=models.TextField(blank=True, null=True),
        ),
    ]
