# Generated by Django 4.2.4 on 2024-07-09 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0107_janitorrecord_change_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='carpenterrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='janitorrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
